-- SQL Logging Session
-- Session ID: 43b4572b-29aa-429a-81aa-a3945557e449
-- Started: 2026-07-08T03:20:38.679Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction
--
-- HAND-FIX after regeneration: core-entity SP calls (spCreateCredentialType/
-- AIAgent/AIAgentPrompt/AIPrompt/FileStorageProvider/Template/TemplateContent)
-- are emitted against [${flyway:defaultSchema}] but must target [${mjSchema}]
-- (__mj). App-schema calls use the literal [__mj_BizAppsCommittees] as-is.

-- Save MJ: Credential Types (core SP call only)
DECLARE @ID_fc4e8123 UNIQUEIDENTIFIER,
@Name_fc4e8123 NVARCHAR(100),
@Description_fc4e8123 NVARCHAR(MAX),
@Category_fc4e8123 NVARCHAR(50),
@FieldSchema_fc4e8123 NVARCHAR(MAX),
@IconClass_fc4e8123 NVARCHAR(100),
@ValidationEndpoint_fc4e8123 NVARCHAR(500)
SET
  @ID_fc4e8123 = 'DAA02013-510D-41F4-BFAA-9250C7BC7D37'
SET
  @Name_fc4e8123 = N'Video Provider OAuth'
SET
  @Description_fc4e8123 = N'OAuth credentials for video conferencing providers (Zoom Server-to-Server, Teams, Google Meet)'
SET
  @Category_fc4e8123 = N'Integration'
SET
  @FieldSchema_fc4e8123 = N'{"type":"object","properties":{"client_id":{"type":"string","title":"Client ID / Service Account Email"},"client_secret":{"type":"string","title":"Client Secret / Private Key PEM"},"account_id":{"type":"string","title":"Account ID (Zoom) / Tenant ID (Teams) / Impersonated User (Google)"},"organizer_user_id":{"type":"string","title":"Organizer User ID (Teams only) — AAD Object ID or UPN"}},"required":["client_id","client_secret","account_id"]}' EXEC [${mjSchema}].spCreateCredentialType @ID = @ID_fc4e8123,
  @Name = @Name_fc4e8123,
  @Description = @Description_fc4e8123,
  @Category = @Category_fc4e8123,
  @FieldSchema = @FieldSchema_fc4e8123,
  @IconClass = @IconClass_fc4e8123,
  @IconClass_Clear = 1,
  @ValidationEndpoint = @ValidationEndpoint_fc4e8123,
  @ValidationEndpoint_Clear = 1;

GO

-- Save Committees: Types (core SP call only)
DECLARE @ID_2e011c20 UNIQUEIDENTIFIER,
@Name_2e011c20 NVARCHAR(100),
@Description_2e011c20 NVARCHAR(MAX),
@IsStandards_2e011c20 BIT,
@DefaultTermMonths_2e011c20 INT,
@IconClass_2e011c20 NVARCHAR(100)
SET
  @ID_2e011c20 = 'DDAB76A3-49C0-400F-A3D2-E525E0B6801D'
SET
  @Name_2e011c20 = N'Board of Directors'
SET
  @Description_2e011c20 = N'Governing board with fiduciary responsibility'
SET
  @IsStandards_2e011c20 = 0
SET
  @DefaultTermMonths_2e011c20 = 12
SET
  @IconClass_2e011c20 = N'fa-solid fa-landmark' EXEC [__mj_BizAppsCommittees].spCreateType @ID = @ID_2e011c20,
  @Name = @Name_2e011c20,
  @Description = @Description_2e011c20,
  @IsStandards = @IsStandards_2e011c20,
  @DefaultTermMonths = @DefaultTermMonths_2e011c20,
  @IconClass = @IconClass_2e011c20;

GO

-- Save Committees: Types (core SP call only)
DECLARE @ID_10d800e6 UNIQUEIDENTIFIER,
@Name_10d800e6 NVARCHAR(100),
@Description_10d800e6 NVARCHAR(MAX),
@IsStandards_10d800e6 BIT,
@DefaultTermMonths_10d800e6 INT,
@IconClass_10d800e6 NVARCHAR(100)
SET
  @ID_10d800e6 = '1AA03C7C-27E0-44A3-B24F-681AAC0CE092'
SET
  @Name_10d800e6 = N'Standing Committee'
SET
  @Description_10d800e6 = N'Permanent committee with ongoing responsibilities'
SET
  @IsStandards_10d800e6 = 0
SET
  @DefaultTermMonths_10d800e6 = 12
SET
  @IconClass_10d800e6 = N'fa-solid fa-users' EXEC [__mj_BizAppsCommittees].spCreateType @ID = @ID_10d800e6,
  @Name = @Name_10d800e6,
  @Description = @Description_10d800e6,
  @IsStandards = @IsStandards_10d800e6,
  @DefaultTermMonths = @DefaultTermMonths_10d800e6,
  @IconClass = @IconClass_10d800e6;

GO

-- Save Committees: Types (core SP call only)
DECLARE @ID_9c5b11be UNIQUEIDENTIFIER,
@Name_9c5b11be NVARCHAR(100),
@Description_9c5b11be NVARCHAR(MAX),
@IsStandards_9c5b11be BIT,
@DefaultTermMonths_9c5b11be INT,
@IconClass_9c5b11be NVARCHAR(100)
SET
  @ID_9c5b11be = '0D118EF8-8297-4E20-A296-8425A0AB147D'
SET
  @Name_9c5b11be = N'Ad Hoc Committee'
SET
  @Description_9c5b11be = N'Temporary committee for specific purpose'
SET
  @IsStandards_9c5b11be = 0
SET
  @IconClass_9c5b11be = N'fa-solid fa-clock' EXEC [__mj_BizAppsCommittees].spCreateType @ID = @ID_9c5b11be,
  @Name = @Name_9c5b11be,
  @Description = @Description_9c5b11be,
  @IsStandards = @IsStandards_9c5b11be,
  @DefaultTermMonths = @DefaultTermMonths_9c5b11be,
  @DefaultTermMonths_Clear = 1,
  @IconClass = @IconClass_9c5b11be;

GO

-- Save Committees: Types (core SP call only)
DECLARE @ID_aea41145 UNIQUEIDENTIFIER,
@Name_aea41145 NVARCHAR(100),
@Description_aea41145 NVARCHAR(MAX),
@IsStandards_aea41145 BIT,
@DefaultTermMonths_aea41145 INT,
@IconClass_aea41145 NVARCHAR(100)
SET
  @ID_aea41145 = '15B526DA-737B-453A-96C2-FF5F3A72423B'
SET
  @Name_aea41145 = N'Workgroup'
SET
  @Description_aea41145 = N'Task-focused group with defined deliverables'
SET
  @IsStandards_aea41145 = 0
SET
  @IconClass_aea41145 = N'fa-solid fa-briefcase' EXEC [__mj_BizAppsCommittees].spCreateType @ID = @ID_aea41145,
  @Name = @Name_aea41145,
  @Description = @Description_aea41145,
  @IsStandards = @IsStandards_aea41145,
  @DefaultTermMonths = @DefaultTermMonths_aea41145,
  @DefaultTermMonths_Clear = 1,
  @IconClass = @IconClass_aea41145;

GO

-- Save Committees: Types (core SP call only)
DECLARE @ID_2672539d UNIQUEIDENTIFIER,
@Name_2672539d NVARCHAR(100),
@Description_2672539d NVARCHAR(MAX),
@IsStandards_2672539d BIT,
@DefaultTermMonths_2672539d INT,
@IconClass_2672539d NVARCHAR(100)
SET
  @ID_2672539d = 'BD2AF204-1DE5-4CEB-B5CD-65F757272FED'
SET
  @Name_2672539d = N'Standards Working Group'
SET
  @Description_2672539d = N'Committee developing standards or specifications'
SET
  @IsStandards_2672539d = 1
SET
  @IconClass_2672539d = N'fa-solid fa-file-contract' EXEC [__mj_BizAppsCommittees].spCreateType @ID = @ID_2672539d,
  @Name = @Name_2672539d,
  @Description = @Description_2672539d,
  @IsStandards = @IsStandards_2672539d,
  @DefaultTermMonths = @DefaultTermMonths_2672539d,
  @DefaultTermMonths_Clear = 1,
  @IconClass = @IconClass_2672539d;

GO

-- Save Committees: Roles (core SP call only)
DECLARE @ID_35fca4ce UNIQUEIDENTIFIER,
@Name_35fca4ce NVARCHAR(100),
@Description_35fca4ce NVARCHAR(MAX),
@IsOfficer_35fca4ce BIT,
@IsVotingRole_35fca4ce BIT,
@DefaultPermissionsJSON_35fca4ce NVARCHAR(MAX),
@Sequence_35fca4ce INT
SET
  @ID_35fca4ce = '9DD3365E-F51A-4841-B3A2-F7BCB7B227A7'
SET
  @Name_35fca4ce = N'Chair'
SET
  @Description_35fca4ce = N'Leads the committee and runs meetings'
SET
  @IsOfficer_35fca4ce = 1
SET
  @IsVotingRole_35fca4ce = 1
SET
  @Sequence_35fca4ce = 10
EXEC [__mj_BizAppsCommittees].spCreateRole @ID = @ID_35fca4ce,
  @Name = @Name_35fca4ce,
  @Description = @Description_35fca4ce,
  @IsOfficer = @IsOfficer_35fca4ce,
  @IsVotingRole = @IsVotingRole_35fca4ce,
  @DefaultPermissionsJSON = @DefaultPermissionsJSON_35fca4ce,
  @DefaultPermissionsJSON_Clear = 1,
  @Sequence = @Sequence_35fca4ce;

GO

-- Save Committees: Roles (core SP call only)
DECLARE @ID_1a83b86a UNIQUEIDENTIFIER,
@Name_1a83b86a NVARCHAR(100),
@Description_1a83b86a NVARCHAR(MAX),
@IsOfficer_1a83b86a BIT,
@IsVotingRole_1a83b86a BIT,
@DefaultPermissionsJSON_1a83b86a NVARCHAR(MAX),
@Sequence_1a83b86a INT
SET
  @ID_1a83b86a = '84456685-A82A-4EC4-8D13-2D7C78F4BC4B'
SET
  @Name_1a83b86a = N'Vice Chair'
SET
  @Description_1a83b86a = N'Supports chair and leads in their absence'
SET
  @IsOfficer_1a83b86a = 1
SET
  @IsVotingRole_1a83b86a = 1
SET
  @Sequence_1a83b86a = 20
EXEC [__mj_BizAppsCommittees].spCreateRole @ID = @ID_1a83b86a,
  @Name = @Name_1a83b86a,
  @Description = @Description_1a83b86a,
  @IsOfficer = @IsOfficer_1a83b86a,
  @IsVotingRole = @IsVotingRole_1a83b86a,
  @DefaultPermissionsJSON = @DefaultPermissionsJSON_1a83b86a,
  @DefaultPermissionsJSON_Clear = 1,
  @Sequence = @Sequence_1a83b86a;

GO

-- Save Committees: Roles (core SP call only)
DECLARE @ID_ee551426 UNIQUEIDENTIFIER,
@Name_ee551426 NVARCHAR(100),
@Description_ee551426 NVARCHAR(MAX),
@IsOfficer_ee551426 BIT,
@IsVotingRole_ee551426 BIT,
@DefaultPermissionsJSON_ee551426 NVARCHAR(MAX),
@Sequence_ee551426 INT
SET
  @ID_ee551426 = '8D87B1BD-3653-462F-B99E-F639186B243A'
SET
  @Name_ee551426 = N'Secretary'
SET
  @Description_ee551426 = N'Records minutes and manages documentation'
SET
  @IsOfficer_ee551426 = 1
SET
  @IsVotingRole_ee551426 = 1
SET
  @Sequence_ee551426 = 30
EXEC [__mj_BizAppsCommittees].spCreateRole @ID = @ID_ee551426,
  @Name = @Name_ee551426,
  @Description = @Description_ee551426,
  @IsOfficer = @IsOfficer_ee551426,
  @IsVotingRole = @IsVotingRole_ee551426,
  @DefaultPermissionsJSON = @DefaultPermissionsJSON_ee551426,
  @DefaultPermissionsJSON_Clear = 1,
  @Sequence = @Sequence_ee551426;

GO

-- Save Committees: Roles (core SP call only)
DECLARE @ID_ce76623e UNIQUEIDENTIFIER,
@Name_ce76623e NVARCHAR(100),
@Description_ce76623e NVARCHAR(MAX),
@IsOfficer_ce76623e BIT,
@IsVotingRole_ce76623e BIT,
@DefaultPermissionsJSON_ce76623e NVARCHAR(MAX),
@Sequence_ce76623e INT
SET
  @ID_ce76623e = 'D329D503-C280-45C4-9265-DBA4AC3FF8BA'
SET
  @Name_ce76623e = N'Treasurer'
SET
  @Description_ce76623e = N'Manages committee finances and reporting'
SET
  @IsOfficer_ce76623e = 1
SET
  @IsVotingRole_ce76623e = 1
SET
  @Sequence_ce76623e = 40
EXEC [__mj_BizAppsCommittees].spCreateRole @ID = @ID_ce76623e,
  @Name = @Name_ce76623e,
  @Description = @Description_ce76623e,
  @IsOfficer = @IsOfficer_ce76623e,
  @IsVotingRole = @IsVotingRole_ce76623e,
  @DefaultPermissionsJSON = @DefaultPermissionsJSON_ce76623e,
  @DefaultPermissionsJSON_Clear = 1,
  @Sequence = @Sequence_ce76623e;

GO

-- Save Committees: Roles (core SP call only)
DECLARE @ID_d0c2361b UNIQUEIDENTIFIER,
@Name_d0c2361b NVARCHAR(100),
@Description_d0c2361b NVARCHAR(MAX),
@IsOfficer_d0c2361b BIT,
@IsVotingRole_d0c2361b BIT,
@DefaultPermissionsJSON_d0c2361b NVARCHAR(MAX),
@Sequence_d0c2361b INT
SET
  @ID_d0c2361b = 'D0409541-ABAA-4780-8E0A-2A07E78E15E3'
SET
  @Name_d0c2361b = N'Member'
SET
  @Description_d0c2361b = N'Voting member of the committee'
SET
  @IsOfficer_d0c2361b = 0
SET
  @IsVotingRole_d0c2361b = 1
SET
  @Sequence_d0c2361b = 100
EXEC [__mj_BizAppsCommittees].spCreateRole @ID = @ID_d0c2361b,
  @Name = @Name_d0c2361b,
  @Description = @Description_d0c2361b,
  @IsOfficer = @IsOfficer_d0c2361b,
  @IsVotingRole = @IsVotingRole_d0c2361b,
  @DefaultPermissionsJSON = @DefaultPermissionsJSON_d0c2361b,
  @DefaultPermissionsJSON_Clear = 1,
  @Sequence = @Sequence_d0c2361b;

GO

-- Save Committees: Roles (core SP call only)
DECLARE @ID_57a426ca UNIQUEIDENTIFIER,
@Name_57a426ca NVARCHAR(100),
@Description_57a426ca NVARCHAR(MAX),
@IsOfficer_57a426ca BIT,
@IsVotingRole_57a426ca BIT,
@DefaultPermissionsJSON_57a426ca NVARCHAR(MAX),
@Sequence_57a426ca INT
SET
  @ID_57a426ca = 'CA5CD32E-2869-4904-93F4-1E63630BF84A'
SET
  @Name_57a426ca = N'Non-Voting Member'
SET
  @Description_57a426ca = N'Participates but does not vote'
SET
  @IsOfficer_57a426ca = 0
SET
  @IsVotingRole_57a426ca = 0
SET
  @Sequence_57a426ca = 110
EXEC [__mj_BizAppsCommittees].spCreateRole @ID = @ID_57a426ca,
  @Name = @Name_57a426ca,
  @Description = @Description_57a426ca,
  @IsOfficer = @IsOfficer_57a426ca,
  @IsVotingRole = @IsVotingRole_57a426ca,
  @DefaultPermissionsJSON = @DefaultPermissionsJSON_57a426ca,
  @DefaultPermissionsJSON_Clear = 1,
  @Sequence = @Sequence_57a426ca;

GO

-- Save Committees: Roles (core SP call only)
DECLARE @ID_9385ae58 UNIQUEIDENTIFIER,
@Name_9385ae58 NVARCHAR(100),
@Description_9385ae58 NVARCHAR(MAX),
@IsOfficer_9385ae58 BIT,
@IsVotingRole_9385ae58 BIT,
@DefaultPermissionsJSON_9385ae58 NVARCHAR(MAX),
@Sequence_9385ae58 INT
SET
  @ID_9385ae58 = 'D1C2B6D4-9119-4D3E-A0D3-19EFBE56F2A9'
SET
  @Name_9385ae58 = N'Liaison'
SET
  @Description_9385ae58 = N'Represents another group or organization'
SET
  @IsOfficer_9385ae58 = 0
SET
  @IsVotingRole_9385ae58 = 0
SET
  @Sequence_9385ae58 = 120
EXEC [__mj_BizAppsCommittees].spCreateRole @ID = @ID_9385ae58,
  @Name = @Name_9385ae58,
  @Description = @Description_9385ae58,
  @IsOfficer = @IsOfficer_9385ae58,
  @IsVotingRole = @IsVotingRole_9385ae58,
  @DefaultPermissionsJSON = @DefaultPermissionsJSON_9385ae58,
  @DefaultPermissionsJSON_Clear = 1,
  @Sequence = @Sequence_9385ae58;

GO

-- Save Committees: Roles (core SP call only)
DECLARE @ID_93cbbe92 UNIQUEIDENTIFIER,
@Name_93cbbe92 NVARCHAR(100),
@Description_93cbbe92 NVARCHAR(MAX),
@IsOfficer_93cbbe92 BIT,
@IsVotingRole_93cbbe92 BIT,
@DefaultPermissionsJSON_93cbbe92 NVARCHAR(MAX),
@Sequence_93cbbe92 INT
SET
  @ID_93cbbe92 = '8764A17C-1690-4E8D-AFF1-4CC6D4CA8E54'
SET
  @Name_93cbbe92 = N'Advisor'
SET
  @Description_93cbbe92 = N'Provides expertise without membership'
SET
  @IsOfficer_93cbbe92 = 0
SET
  @IsVotingRole_93cbbe92 = 0
SET
  @Sequence_93cbbe92 = 130
EXEC [__mj_BizAppsCommittees].spCreateRole @ID = @ID_93cbbe92,
  @Name = @Name_93cbbe92,
  @Description = @Description_93cbbe92,
  @IsOfficer = @IsOfficer_93cbbe92,
  @IsVotingRole = @IsVotingRole_93cbbe92,
  @DefaultPermissionsJSON = @DefaultPermissionsJSON_93cbbe92,
  @DefaultPermissionsJSON_Clear = 1,
  @Sequence = @Sequence_93cbbe92;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_2d98802c UNIQUEIDENTIFIER,
@Name_2d98802c NVARCHAR(100),
@Description_2d98802c NVARCHAR(MAX),
@ExtendedEntityID_2d98802c UNIQUEIDENTIFIER,
@IconClass_2d98802c NVARCHAR(100)
SET
  @ID_2d98802c = '3C82A0CF-98B8-49C4-8E3A-7A330EC2FE99'
SET
  @Name_2d98802c = N'Document'
SET
  @Description_2d98802c = N'General document'
SET
  @IconClass_2d98802c = N'fa-solid fa-file' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_2d98802c,
  @Name = @Name_2d98802c,
  @Description = @Description_2d98802c,
  @ExtendedEntityID = @ExtendedEntityID_2d98802c,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_2d98802c;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_4ee1efa4 UNIQUEIDENTIFIER,
@Name_4ee1efa4 NVARCHAR(100),
@Description_4ee1efa4 NVARCHAR(MAX),
@ExtendedEntityID_4ee1efa4 UNIQUEIDENTIFIER,
@IconClass_4ee1efa4 NVARCHAR(100)
SET
  @ID_4ee1efa4 = 'EBFE95A6-A754-4BA1-904F-7A542AD8E77E'
SET
  @Name_4ee1efa4 = N'Spreadsheet'
SET
  @Description_4ee1efa4 = N'Spreadsheet or data file'
SET
  @IconClass_4ee1efa4 = N'fa-solid fa-file-excel' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_4ee1efa4,
  @Name = @Name_4ee1efa4,
  @Description = @Description_4ee1efa4,
  @ExtendedEntityID = @ExtendedEntityID_4ee1efa4,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_4ee1efa4;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_a6fb1ad8 UNIQUEIDENTIFIER,
@Name_a6fb1ad8 NVARCHAR(100),
@Description_a6fb1ad8 NVARCHAR(MAX),
@ExtendedEntityID_a6fb1ad8 UNIQUEIDENTIFIER,
@IconClass_a6fb1ad8 NVARCHAR(100)
SET
  @ID_a6fb1ad8 = 'B5C3AF85-51BC-4A1D-BDDB-B8FB6E689A20'
SET
  @Name_a6fb1ad8 = N'Presentation'
SET
  @Description_a6fb1ad8 = N'Slide deck or presentation'
SET
  @IconClass_a6fb1ad8 = N'fa-solid fa-file-powerpoint' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_a6fb1ad8,
  @Name = @Name_a6fb1ad8,
  @Description = @Description_a6fb1ad8,
  @ExtendedEntityID = @ExtendedEntityID_a6fb1ad8,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_a6fb1ad8;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_7fe38779 UNIQUEIDENTIFIER,
@Name_7fe38779 NVARCHAR(100),
@Description_7fe38779 NVARCHAR(MAX),
@ExtendedEntityID_7fe38779 UNIQUEIDENTIFIER,
@IconClass_7fe38779 NVARCHAR(100)
SET
  @ID_7fe38779 = 'D0E9FDD1-136E-4F3D-9916-37E703B29DA3'
SET
  @Name_7fe38779 = N'Minutes'
SET
  @Description_7fe38779 = N'Meeting minutes with approval tracking'
SET
  @IconClass_7fe38779 = N'fa-solid fa-clipboard-check' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_7fe38779,
  @Name = @Name_7fe38779,
  @Description = @Description_7fe38779,
  @ExtendedEntityID = @ExtendedEntityID_7fe38779,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_7fe38779;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_6a35fc60 UNIQUEIDENTIFIER,
@Name_6a35fc60 NVARCHAR(100),
@Description_6a35fc60 NVARCHAR(MAX),
@ExtendedEntityID_6a35fc60 UNIQUEIDENTIFIER,
@IconClass_6a35fc60 NVARCHAR(100)
SET
  @ID_6a35fc60 = 'D09E0721-0059-4A67-B13A-D4CD42584EF4'
SET
  @Name_6a35fc60 = N'Agenda'
SET
  @Description_6a35fc60 = N'Meeting agenda document'
SET
  @IconClass_6a35fc60 = N'fa-solid fa-list-check' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_6a35fc60,
  @Name = @Name_6a35fc60,
  @Description = @Description_6a35fc60,
  @ExtendedEntityID = @ExtendedEntityID_6a35fc60,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_6a35fc60;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_8287f036 UNIQUEIDENTIFIER,
@Name_8287f036 NVARCHAR(100),
@Description_8287f036 NVARCHAR(MAX),
@ExtendedEntityID_8287f036 UNIQUEIDENTIFIER,
@IconClass_8287f036 NVARCHAR(100)
SET
  @ID_8287f036 = '0EDC9CFE-12BE-4908-B2A4-75A1C0ABE06A'
SET
  @Name_8287f036 = N'Recording'
SET
  @Description_8287f036 = N'Audio or video recording'
SET
  @IconClass_8287f036 = N'fa-solid fa-video' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_8287f036,
  @Name = @Name_8287f036,
  @Description = @Description_8287f036,
  @ExtendedEntityID = @ExtendedEntityID_8287f036,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_8287f036;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_979e2725 UNIQUEIDENTIFIER,
@Name_979e2725 NVARCHAR(100),
@Description_979e2725 NVARCHAR(MAX),
@ExtendedEntityID_979e2725 UNIQUEIDENTIFIER,
@IconClass_979e2725 NVARCHAR(100)
SET
  @ID_979e2725 = 'D932148F-9A32-42AB-9D20-0F163B0FE392'
SET
  @Name_979e2725 = N'Transcript'
SET
  @Description_979e2725 = N'Meeting transcript'
SET
  @IconClass_979e2725 = N'fa-solid fa-closed-captioning' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_979e2725,
  @Name = @Name_979e2725,
  @Description = @Description_979e2725,
  @ExtendedEntityID = @ExtendedEntityID_979e2725,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_979e2725;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_1465a930 UNIQUEIDENTIFIER,
@Name_1465a930 NVARCHAR(100),
@Description_1465a930 NVARCHAR(MAX),
@ExtendedEntityID_1465a930 UNIQUEIDENTIFIER,
@IconClass_1465a930 NVARCHAR(100)
SET
  @ID_1465a930 = '2204BF1E-5FDE-4B69-84A1-D12AFFDAE54D'
SET
  @Name_1465a930 = N'Image'
SET
  @Description_1465a930 = N'Image or diagram'
SET
  @IconClass_1465a930 = N'fa-solid fa-image' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_1465a930,
  @Name = @Name_1465a930,
  @Description = @Description_1465a930,
  @ExtendedEntityID = @ExtendedEntityID_1465a930,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_1465a930;

GO

-- Save Committees: Artifact Types (core SP call only)
DECLARE @ID_d71f04e5 UNIQUEIDENTIFIER,
@Name_d71f04e5 NVARCHAR(100),
@Description_d71f04e5 NVARCHAR(MAX),
@ExtendedEntityID_d71f04e5 UNIQUEIDENTIFIER,
@IconClass_d71f04e5 NVARCHAR(100)
SET
  @ID_d71f04e5 = 'A2C76DBA-657F-4CB0-B20D-E7B85D3A1881'
SET
  @Name_d71f04e5 = N'Other'
SET
  @Description_d71f04e5 = N'Other artifact type'
SET
  @IconClass_d71f04e5 = N'fa-solid fa-file-lines' EXEC [__mj_BizAppsCommittees].spCreateArtifactType @ID = @ID_d71f04e5,
  @Name = @Name_d71f04e5,
  @Description = @Description_d71f04e5,
  @ExtendedEntityID = @ExtendedEntityID_d71f04e5,
  @ExtendedEntityID_Clear = 1,
  @IconClass = @IconClass_d71f04e5;

GO

-- Save MJ: File Storage Providers (core SP call only)
DECLARE @ID_2cbc348a UNIQUEIDENTIFIER,
@Name_2cbc348a NVARCHAR(50),
@Description_2cbc348a NVARCHAR(MAX),
@ServerDriverKey_2cbc348a NVARCHAR(100),
@ClientDriverKey_2cbc348a NVARCHAR(100),
@Priority_2cbc348a INT,
@IsActive_2cbc348a BIT,
@SupportsSearch_2cbc348a BIT,
@Configuration_2cbc348a NVARCHAR(MAX),
@RequiresOAuth_2cbc348a BIT
SET
  @ID_2cbc348a = '93DBCFC9-5B2A-48D6-9D95-E93B319C88E5'
SET
  @Name_2cbc348a = N'External URL'
SET
  @Description_2cbc348a = N'Reference-only provider for externally-hosted documents. The full URL is stored in each File''s ProviderKey; no bytes are stored or uploaded. Used by the Committees document feature for linking Google Docs, SharePoint, etc.'
SET
  @ServerDriverKey_2cbc348a = N'ExternalURL'
SET
  @ClientDriverKey_2cbc348a = N'ExternalURL'
SET
  @Priority_2cbc348a = 0
SET
  @IsActive_2cbc348a = 1
SET
  @SupportsSearch_2cbc348a = 0
SET
  @RequiresOAuth_2cbc348a = 0
EXEC [${mjSchema}].spCreateFileStorageProvider @ID = @ID_2cbc348a,
  @Name = @Name_2cbc348a,
  @Description = @Description_2cbc348a,
  @ServerDriverKey = @ServerDriverKey_2cbc348a,
  @ClientDriverKey = @ClientDriverKey_2cbc348a,
  @Priority = @Priority_2cbc348a,
  @IsActive = @IsActive_2cbc348a,
  @SupportsSearch = @SupportsSearch_2cbc348a,
  @Configuration = @Configuration_2cbc348a,
  @Configuration_Clear = 1,
  @RequiresOAuth = @RequiresOAuth_2cbc348a;

GO

-- Save MJ: Templates (core SP call only)
DECLARE @ID_0989e987 UNIQUEIDENTIFIER,
@Name_0989e987 NVARCHAR(255),
@Description_0989e987 NVARCHAR(MAX),
@CategoryID_0989e987 UNIQUEIDENTIFIER,
@UserPrompt_0989e987 NVARCHAR(MAX),
@UserID_0989e987 UNIQUEIDENTIFIER,
@ActiveAt_0989e987 DATETIMEOFFSET,
@DisabledAt_0989e987 DATETIMEOFFSET,
@IsActive_0989e987 BIT
SET
  @ID_0989e987 = '96986210-426e-4e87-832f-16057b377926'
SET
  @Name_0989e987 = N'Committee Importer - System Prompt'
SET
  @Description_0989e987 = N'Template for AI Prompt: Committee Importer - System Prompt'
SET
  @CategoryID_0989e987 = 'B61B01C3-2DD1-4FFA-AE77-6DE9765BCA68'
SET
  @UserID_0989e987 = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @IsActive_0989e987 = 1
EXEC [${mjSchema}].spCreateTemplate @ID = @ID_0989e987,
  @Name = @Name_0989e987,
  @Description = @Description_0989e987,
  @CategoryID = @CategoryID_0989e987,
  @UserPrompt = @UserPrompt_0989e987,
  @UserPrompt_Clear = 1,
  @UserID = @UserID_0989e987,
  @ActiveAt = @ActiveAt_0989e987,
  @ActiveAt_Clear = 1,
  @DisabledAt = @DisabledAt_0989e987,
  @DisabledAt_Clear = 1,
  @IsActive = @IsActive_0989e987;

GO

-- Save MJ: Template Contents (core SP call only)
DECLARE @ID_4e5d7f12 UNIQUEIDENTIFIER,
@TemplateID_4e5d7f12 UNIQUEIDENTIFIER,
@TypeID_4e5d7f12 UNIQUEIDENTIFIER,
@TemplateText_4e5d7f12 NVARCHAR(MAX),
@Priority_4e5d7f12 INT,
@IsActive_4e5d7f12 BIT
SET
  @ID_4e5d7f12 = 'c5340541-290e-49ff-9196-c8532d584b48'
SET
  @TemplateID_4e5d7f12 = '96986210-426E-4E87-832F-16057B377926'
SET
  @TypeID_4e5d7f12 = 'E7AFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @TemplateText_4e5d7f12 = N'# Committee Importer

You are a data extraction specialist. A user has uploaded a spreadsheet (Excel or CSV) containing committee records for an association. Your job is to extract the data into a structured **ImportPlan** JSON object that downstream code will use to create database records.

The spreadsheet is attached as an input artifact. You have tools to navigate it: `get_sheets`, `get_sheet_data`, `search_cells`, `aggregate_column`, `get_formulas`. Always start with `get_sheets` to understand the workbook shape before reading data.

## Spreadsheet Shapes You May Encounter

1. **Flat sheet** — one row per membership, with columns like `Committee`, `Person Name`, `Email`, `Role`, `Term Year`, etc. You must derive Committees, Terms, People, and Memberships from a single sheet by deduplicating.
2. **Multi-sheet workbook** — separate sheets for `Committees`, `Terms`, `People`, `Memberships`. Match columns by name (loose, case-insensitive).
3. **Hybrid / messy** — header row may not be row 1; merged cells; multiple tables on one sheet. Use your judgment, prefer the largest contiguous block of data.

## What to Extract

Build an `ImportPlan` object with four arrays. Every row in every array carries an optional `_problems` array describing any concerns.

```json
{
  "committees":  [ /* one entry per unique committee */ ],
  "terms":       [ /* one entry per committee/year combo */ ],
  "people":      [ /* one entry per unique person */ ],
  "memberships": [ /* one entry per unique person+committee+role combo */ ]
}
```

### `committees[]`
- `Name` (string, required)
- `Description` (string, optional)
- `CommitteeType` (string, required) — must be one of: `Board of Directors`, `Standing Committee`, `Ad Hoc Committee`, `Workgroup`, `Standards Working Group`. If unsure, pick the closest match and add a problem.
- `_problems` (array)

### `terms[]`
- `CommitteeRef` (string, required) — must exactly match a committee `Name` from `committees[]`
- `Year` (number, required)
- `StartDate` (ISO date string `YYYY-MM-DD`, required)
- `EndDate` (ISO date string `YYYY-MM-DD`, required)
- `_problems`

### `people[]`
- `FirstName` (string, required)
- `LastName` (string, required)
- `Email` (string, required) — used as the unique key
- `_problems`

### `memberships[]`
- `CommitteeRef` (string, required) — matches `committees[].Name`
- `PersonRef` (string, required) — matches `people[].Email`
- `Role` (string, required) — common values: `Chair`, `Vice Chair`, `Secretary`, `Treasurer`, `Member`. Other values are allowed but flag with a problem.
- `Status` (string, required) — one of: `Active`, `Inactive`, `Pending`. Default to `Active` if missing.
- `_problems`

### `_problems[]` shape
```json
{
  "field": "CommitteeType",
  "severity": "warning",   // or "error"
  "message": "Source value ''Standing Comm'' was mapped to ''Standing Committee''.",
  "suggestedValue": "Standing Committee"
}
```

Use `error` when the row cannot be safely imported as-is (missing required field, unparseable date, malformed email). Use `warning` when you made a best-guess mapping that the user should confirm.

## Rules

- **Dedupe**: same person appearing on multiple committees → one entry in `people[]`, multiple in `memberships[]`. Match people by email (case-insensitive).
- **Flag, don''t guess**: if a `CommitteeType` is ambiguous, pick the most likely value AND add a `warning` problem. Don''t silently coerce.
- **Don''t fabricate**: never invent emails, dates, or names. If a required field is genuinely missing, set it to `null` and add an `error` problem.
- **Date parsing**: accept `MM/DD/YYYY`, `DD/MM/YYYY` (use surrounding context), `YYYY-MM-DD`, and Excel serial numbers. Always emit `YYYY-MM-DD`.
- **Role normalization**: map common variants ("Co-Chair" → `Chair` with warning, "VC" → `Vice Chair`, etc.). Unmappable roles stay as-is with a warning.
- **Empty rows**: skip silently, no problem entries needed.

## Output

Return **only** the `ImportPlan` JSON object as your final payload. No prose, no markdown fencing, no commentary. Downstream code parses your output directly.
'
SET
  @Priority_4e5d7f12 = 1
SET
  @IsActive_4e5d7f12 = 1
EXEC [${mjSchema}].spCreateTemplateContent @ID = @ID_4e5d7f12,
  @TemplateID = @TemplateID_4e5d7f12,
  @TypeID = @TypeID_4e5d7f12,
  @TemplateText = @TemplateText_4e5d7f12,
  @Priority = @Priority_4e5d7f12,
  @IsActive = @IsActive_4e5d7f12;

GO

-- Save MJ: AI Prompts (core SP call only)
DECLARE @ID_c7b5e78a UNIQUEIDENTIFIER,
@Name_c7b5e78a NVARCHAR(255),
@Description_c7b5e78a NVARCHAR(MAX),
@TemplateID_c7b5e78a UNIQUEIDENTIFIER,
@CategoryID_c7b5e78a UNIQUEIDENTIFIER,
@TypeID_c7b5e78a UNIQUEIDENTIFIER,
@Status_c7b5e78a NVARCHAR(50),
@ResponseFormat_c7b5e78a NVARCHAR(20),
@ModelSpecificResponseFormat_c7b5e78a NVARCHAR(MAX),
@AIModelTypeID_c7b5e78a UNIQUEIDENTIFIER,
@MinPowerRank_c7b5e78a INT,
@SelectionStrategy_c7b5e78a NVARCHAR(20),
@PowerPreference_c7b5e78a NVARCHAR(20),
@ParallelizationMode_c7b5e78a NVARCHAR(20),
@ParallelCount_c7b5e78a INT,
@ParallelConfigParam_c7b5e78a NVARCHAR(100),
@OutputType_c7b5e78a NVARCHAR(50),
@OutputExample_c7b5e78a NVARCHAR(MAX),
@ValidationBehavior_c7b5e78a NVARCHAR(50),
@MaxRetries_c7b5e78a INT,
@RetryDelayMS_c7b5e78a INT,
@RetryStrategy_c7b5e78a NVARCHAR(20),
@ResultSelectorPromptID_c7b5e78a UNIQUEIDENTIFIER,
@EnableCaching_c7b5e78a BIT,
@CacheTTLSeconds_c7b5e78a INT,
@CacheMatchType_c7b5e78a NVARCHAR(20),
@CacheSimilarityThreshold_c7b5e78a FLOAT(53),
@CacheMustMatchModel_c7b5e78a BIT,
@CacheMustMatchVendor_c7b5e78a BIT,
@CacheMustMatchAgent_c7b5e78a BIT,
@CacheMustMatchConfig_c7b5e78a BIT,
@PromptRole_c7b5e78a NVARCHAR(20),
@PromptPosition_c7b5e78a NVARCHAR(20),
@Temperature_c7b5e78a DECIMAL(3, 2),
@TopP_c7b5e78a DECIMAL(3, 2),
@TopK_c7b5e78a INT,
@MinP_c7b5e78a DECIMAL(3, 2),
@FrequencyPenalty_c7b5e78a DECIMAL(3, 2),
@PresencePenalty_c7b5e78a DECIMAL(3, 2),
@Seed_c7b5e78a INT,
@StopSequences_c7b5e78a NVARCHAR(1000),
@IncludeLogProbs_c7b5e78a BIT,
@TopLogProbs_c7b5e78a INT,
@FailoverStrategy_c7b5e78a NVARCHAR(50),
@FailoverMaxAttempts_c7b5e78a INT,
@FailoverDelaySeconds_c7b5e78a INT,
@FailoverModelStrategy_c7b5e78a NVARCHAR(50),
@FailoverErrorScope_c7b5e78a NVARCHAR(50),
@EffortLevel_c7b5e78a INT,
@AssistantPrefill_c7b5e78a NVARCHAR(MAX),
@PrefillFallbackMode_c7b5e78a NVARCHAR(20),
@RequireSpecificModels_c7b5e78a BIT
SET
  @ID_c7b5e78a = 'D9514B6F-567B-431B-8718-6C93DFFCD0D9'
SET
  @Name_c7b5e78a = N'Committee Importer - System Prompt'
SET
  @Description_c7b5e78a = N'Extracts committees, terms, people, and memberships from an attached spreadsheet artifact and returns a structured ImportPlan JSON.'
SET
  @TemplateID_c7b5e78a = '96986210-426E-4E87-832F-16057B377926'
SET
  @TypeID_c7b5e78a = 'A6DA423E-F36B-1410-8DAC-00021F8B792E'
SET
  @Status_c7b5e78a = N'Active'
SET
  @ResponseFormat_c7b5e78a = N'JSON'
SET
  @MinPowerRank_c7b5e78a = 0
SET
  @SelectionStrategy_c7b5e78a = N'Default'
SET
  @PowerPreference_c7b5e78a = N'Highest'
SET
  @ParallelizationMode_c7b5e78a = N'None'
SET
  @OutputType_c7b5e78a = N'string'
SET
  @ValidationBehavior_c7b5e78a = N'Warn'
SET
  @MaxRetries_c7b5e78a = 0
SET
  @RetryDelayMS_c7b5e78a = 0
SET
  @RetryStrategy_c7b5e78a = N'Fixed'
SET
  @EnableCaching_c7b5e78a = 0
SET
  @CacheMatchType_c7b5e78a = N'Exact'
SET
  @CacheMustMatchModel_c7b5e78a = 1
SET
  @CacheMustMatchVendor_c7b5e78a = 1
SET
  @CacheMustMatchAgent_c7b5e78a = 0
SET
  @CacheMustMatchConfig_c7b5e78a = 0
SET
  @PromptRole_c7b5e78a = N'System'
SET
  @PromptPosition_c7b5e78a = N'First'
SET
  @IncludeLogProbs_c7b5e78a = 0
SET
  @FailoverStrategy_c7b5e78a = N'SameModelDifferentVendor'
SET
  @FailoverMaxAttempts_c7b5e78a = 3
SET
  @FailoverDelaySeconds_c7b5e78a = 5
SET
  @FailoverModelStrategy_c7b5e78a = N'PreferSameModel'
SET
  @FailoverErrorScope_c7b5e78a = N'All'
SET
  @PrefillFallbackMode_c7b5e78a = N'Ignore'
SET
  @RequireSpecificModels_c7b5e78a = 0
EXEC [${mjSchema}].spCreateAIPrompt @ID = @ID_c7b5e78a,
  @Name = @Name_c7b5e78a,
  @Description = @Description_c7b5e78a,
  @TemplateID = @TemplateID_c7b5e78a,
  @CategoryID = @CategoryID_c7b5e78a,
  @CategoryID_Clear = 1,
  @TypeID = @TypeID_c7b5e78a,
  @Status = @Status_c7b5e78a,
  @ResponseFormat = @ResponseFormat_c7b5e78a,
  @ModelSpecificResponseFormat = @ModelSpecificResponseFormat_c7b5e78a,
  @ModelSpecificResponseFormat_Clear = 1,
  @AIModelTypeID = @AIModelTypeID_c7b5e78a,
  @AIModelTypeID_Clear = 1,
  @MinPowerRank = @MinPowerRank_c7b5e78a,
  @SelectionStrategy = @SelectionStrategy_c7b5e78a,
  @PowerPreference = @PowerPreference_c7b5e78a,
  @ParallelizationMode = @ParallelizationMode_c7b5e78a,
  @ParallelCount = @ParallelCount_c7b5e78a,
  @ParallelCount_Clear = 1,
  @ParallelConfigParam = @ParallelConfigParam_c7b5e78a,
  @ParallelConfigParam_Clear = 1,
  @OutputType = @OutputType_c7b5e78a,
  @OutputExample = @OutputExample_c7b5e78a,
  @OutputExample_Clear = 1,
  @ValidationBehavior = @ValidationBehavior_c7b5e78a,
  @MaxRetries = @MaxRetries_c7b5e78a,
  @RetryDelayMS = @RetryDelayMS_c7b5e78a,
  @RetryStrategy = @RetryStrategy_c7b5e78a,
  @ResultSelectorPromptID = @ResultSelectorPromptID_c7b5e78a,
  @ResultSelectorPromptID_Clear = 1,
  @EnableCaching = @EnableCaching_c7b5e78a,
  @CacheTTLSeconds = @CacheTTLSeconds_c7b5e78a,
  @CacheTTLSeconds_Clear = 1,
  @CacheMatchType = @CacheMatchType_c7b5e78a,
  @CacheSimilarityThreshold = @CacheSimilarityThreshold_c7b5e78a,
  @CacheSimilarityThreshold_Clear = 1,
  @CacheMustMatchModel = @CacheMustMatchModel_c7b5e78a,
  @CacheMustMatchVendor = @CacheMustMatchVendor_c7b5e78a,
  @CacheMustMatchAgent = @CacheMustMatchAgent_c7b5e78a,
  @CacheMustMatchConfig = @CacheMustMatchConfig_c7b5e78a,
  @PromptRole = @PromptRole_c7b5e78a,
  @PromptPosition = @PromptPosition_c7b5e78a,
  @Temperature = @Temperature_c7b5e78a,
  @Temperature_Clear = 1,
  @TopP = @TopP_c7b5e78a,
  @TopP_Clear = 1,
  @TopK = @TopK_c7b5e78a,
  @TopK_Clear = 1,
  @MinP = @MinP_c7b5e78a,
  @MinP_Clear = 1,
  @FrequencyPenalty = @FrequencyPenalty_c7b5e78a,
  @FrequencyPenalty_Clear = 1,
  @PresencePenalty = @PresencePenalty_c7b5e78a,
  @PresencePenalty_Clear = 1,
  @Seed = @Seed_c7b5e78a,
  @Seed_Clear = 1,
  @StopSequences = @StopSequences_c7b5e78a,
  @StopSequences_Clear = 1,
  @IncludeLogProbs = @IncludeLogProbs_c7b5e78a,
  @TopLogProbs = @TopLogProbs_c7b5e78a,
  @TopLogProbs_Clear = 1,
  @FailoverStrategy = @FailoverStrategy_c7b5e78a,
  @FailoverMaxAttempts = @FailoverMaxAttempts_c7b5e78a,
  @FailoverDelaySeconds = @FailoverDelaySeconds_c7b5e78a,
  @FailoverModelStrategy = @FailoverModelStrategy_c7b5e78a,
  @FailoverErrorScope = @FailoverErrorScope_c7b5e78a,
  @EffortLevel = @EffortLevel_c7b5e78a,
  @EffortLevel_Clear = 1,
  @AssistantPrefill = @AssistantPrefill_c7b5e78a,
  @AssistantPrefill_Clear = 1,
  @PrefillFallbackMode = @PrefillFallbackMode_c7b5e78a,
  @RequireSpecificModels = @RequireSpecificModels_c7b5e78a;

GO

-- Save MJ: AI Agents (core SP call only)
DECLARE @ID_70bf2ca4 UNIQUEIDENTIFIER,
@Name_70bf2ca4 NVARCHAR(255),
@Description_70bf2ca4 NVARCHAR(MAX),
@LogoURL_70bf2ca4 NVARCHAR(255),
@ParentID_70bf2ca4 UNIQUEIDENTIFIER,
@ExposeAsAction_70bf2ca4 BIT,
@ExecutionOrder_70bf2ca4 INT,
@ExecutionMode_70bf2ca4 NVARCHAR(20),
@EnableContextCompression_70bf2ca4 BIT,
@ContextCompressionMessageThreshold_70bf2ca4 INT,
@ContextCompressionPromptID_70bf2ca4 UNIQUEIDENTIFIER,
@ContextCompressionMessageRetentionCount_70bf2ca4 INT,
@TypeID_70bf2ca4 UNIQUEIDENTIFIER,
@Status_70bf2ca4 NVARCHAR(20),
@DriverClass_70bf2ca4 NVARCHAR(255),
@IconClass_70bf2ca4 NVARCHAR(100),
@ModelSelectionMode_70bf2ca4 NVARCHAR(50),
@PayloadDownstreamPaths_70bf2ca4 NVARCHAR(MAX),
@PayloadUpstreamPaths_70bf2ca4 NVARCHAR(MAX),
@PayloadSelfReadPaths_70bf2ca4 NVARCHAR(MAX),
@PayloadSelfWritePaths_70bf2ca4 NVARCHAR(MAX),
@PayloadScope_70bf2ca4 NVARCHAR(MAX),
@FinalPayloadValidation_70bf2ca4 NVARCHAR(MAX),
@FinalPayloadValidationMode_70bf2ca4 NVARCHAR(25),
@FinalPayloadValidationMaxRetries_70bf2ca4 INT,
@MaxCostPerRun_70bf2ca4 DECIMAL(10, 4),
@MaxTokensPerRun_70bf2ca4 INT,
@MaxIterationsPerRun_70bf2ca4 INT,
@MaxTimePerRun_70bf2ca4 INT,
@MinExecutionsPerRun_70bf2ca4 INT,
@MaxExecutionsPerRun_70bf2ca4 INT,
@StartingPayloadValidation_70bf2ca4 NVARCHAR(MAX),
@StartingPayloadValidationMode_70bf2ca4 NVARCHAR(25),
@DefaultPromptEffortLevel_70bf2ca4 INT,
@ChatHandlingOption_70bf2ca4 NVARCHAR(30),
@DefaultArtifactTypeID_70bf2ca4 UNIQUEIDENTIFIER,
@OwnerUserID_70bf2ca4 UNIQUEIDENTIFIER,
@InvocationMode_70bf2ca4 NVARCHAR(20),
@ArtifactCreationMode_70bf2ca4 NVARCHAR(20),
@FunctionalRequirements_70bf2ca4 NVARCHAR(MAX),
@TechnicalDesign_70bf2ca4 NVARCHAR(MAX),
@InjectNotes_70bf2ca4 BIT,
@MaxNotesToInject_70bf2ca4 INT,
@NoteInjectionStrategy_70bf2ca4 NVARCHAR(20),
@InjectExamples_70bf2ca4 BIT,
@MaxExamplesToInject_70bf2ca4 INT,
@ExampleInjectionStrategy_70bf2ca4 NVARCHAR(20),
@IsRestricted_70bf2ca4 BIT,
@MessageMode_70bf2ca4 NVARCHAR(50),
@MaxMessages_70bf2ca4 INT,
@AttachmentStorageProviderID_70bf2ca4 UNIQUEIDENTIFIER,
@AttachmentRootPath_70bf2ca4 NVARCHAR(500),
@InlineStorageThresholdBytes_70bf2ca4 INT,
@AgentTypePromptParams_70bf2ca4 NVARCHAR(MAX),
@ScopeConfig_70bf2ca4 NVARCHAR(MAX),
@NoteRetentionDays_70bf2ca4 INT,
@ExampleRetentionDays_70bf2ca4 INT,
@AutoArchiveEnabled_70bf2ca4 BIT,
@RerankerConfiguration_70bf2ca4 NVARCHAR(MAX),
@CategoryID_70bf2ca4 UNIQUEIDENTIFIER,
@AllowEphemeralClientTools_70bf2ca4 BIT,
@DefaultStorageAccountID_70bf2ca4 UNIQUEIDENTIFIER,
@SearchScopeAccess_70bf2ca4 NVARCHAR(20),
@AcceptUnregisteredFiles_70bf2ca4 BIT,
@DefaultCoAgentID_70bf2ca4 UNIQUEIDENTIFIER,
@TypeConfiguration_70bf2ca4 NVARCHAR(MAX),
@AllowMemoryWrite_70bf2ca4 BIT,
@RecordingDefault_70bf2ca4 NVARCHAR(20),
@RecordingStorageProviderID_70bf2ca4 UNIQUEIDENTIFIER,
@DefaultMediaCollectionID_70bf2ca4 UNIQUEIDENTIFIER,
@SupportsPlanMode_70bf2ca4 BIT,
@AcceptsSkills_70bf2ca4 NVARCHAR(20),
@SkillActivationMode_70bf2ca4 NVARCHAR(20),
@RequirePlanMode_70bf2ca4 BIT
SET
  @ID_70bf2ca4 = 'EA768C7C-66B6-4A60-BB5E-2D669E571FB1'
SET
  @Name_70bf2ca4 = N'Committee Importer'
SET
  @Description_70bf2ca4 = N'Extracts committees, terms, people, and memberships from a spreadsheet artifact and returns a structured ImportPlan JSON. Used by the Committee Management bulk-import flow.'
SET
  @ExposeAsAction_70bf2ca4 = 0
SET
  @ExecutionOrder_70bf2ca4 = 0
SET
  @ExecutionMode_70bf2ca4 = N'Sequential'
SET
  @EnableContextCompression_70bf2ca4 = 0
SET
  @TypeID_70bf2ca4 = 'F7926101-5099-4FA5-836A-479D9707C818'
SET
  @Status_70bf2ca4 = N'Active'
SET
  @IconClass_70bf2ca4 = N'fa-solid fa-file-import'
SET
  @ModelSelectionMode_70bf2ca4 = N'Agent'
SET
  @PayloadDownstreamPaths_70bf2ca4 = N'["*"]'
SET
  @PayloadUpstreamPaths_70bf2ca4 = N'["*"]'
SET
  @FinalPayloadValidationMode_70bf2ca4 = N'Retry'
SET
  @FinalPayloadValidationMaxRetries_70bf2ca4 = 3
SET
  @MaxIterationsPerRun_70bf2ca4 = 8
SET
  @StartingPayloadValidationMode_70bf2ca4 = N'Fail'
SET
  @InvocationMode_70bf2ca4 = N'Any'
SET
  @ArtifactCreationMode_70bf2ca4 = N'Always'
SET
  @InjectNotes_70bf2ca4 = 1
SET
  @MaxNotesToInject_70bf2ca4 = 5
SET
  @NoteInjectionStrategy_70bf2ca4 = N'Relevant'
SET
  @InjectExamples_70bf2ca4 = 0
SET
  @MaxExamplesToInject_70bf2ca4 = 3
SET
  @ExampleInjectionStrategy_70bf2ca4 = N'Semantic'
SET
  @IsRestricted_70bf2ca4 = 0
SET
  @MessageMode_70bf2ca4 = N'None'
SET
  @NoteRetentionDays_70bf2ca4 = 90
SET
  @ExampleRetentionDays_70bf2ca4 = 180
SET
  @AutoArchiveEnabled_70bf2ca4 = 1
SET
  @AllowEphemeralClientTools_70bf2ca4 = 1
SET
  @SearchScopeAccess_70bf2ca4 = N'None'
SET
  @AcceptUnregisteredFiles_70bf2ca4 = 0
SET
  @AllowMemoryWrite_70bf2ca4 = 1
SET
  @SupportsPlanMode_70bf2ca4 = 1
SET
  @AcceptsSkills_70bf2ca4 = N'None'
SET
  @SkillActivationMode_70bf2ca4 = N'RequestedOnly'
SET
  @RequirePlanMode_70bf2ca4 = 0
EXEC [${mjSchema}].spCreateAIAgent @ID = @ID_70bf2ca4,
  @Name = @Name_70bf2ca4,
  @Description = @Description_70bf2ca4,
  @LogoURL = @LogoURL_70bf2ca4,
  @LogoURL_Clear = 1,
  @ParentID = @ParentID_70bf2ca4,
  @ParentID_Clear = 1,
  @ExposeAsAction = @ExposeAsAction_70bf2ca4,
  @ExecutionOrder = @ExecutionOrder_70bf2ca4,
  @ExecutionMode = @ExecutionMode_70bf2ca4,
  @EnableContextCompression = @EnableContextCompression_70bf2ca4,
  @ContextCompressionMessageThreshold = @ContextCompressionMessageThreshold_70bf2ca4,
  @ContextCompressionMessageThreshold_Clear = 1,
  @ContextCompressionPromptID = @ContextCompressionPromptID_70bf2ca4,
  @ContextCompressionPromptID_Clear = 1,
  @ContextCompressionMessageRetentionCount = @ContextCompressionMessageRetentionCount_70bf2ca4,
  @ContextCompressionMessageRetentionCount_Clear = 1,
  @TypeID = @TypeID_70bf2ca4,
  @Status = @Status_70bf2ca4,
  @DriverClass = @DriverClass_70bf2ca4,
  @DriverClass_Clear = 1,
  @IconClass = @IconClass_70bf2ca4,
  @ModelSelectionMode = @ModelSelectionMode_70bf2ca4,
  @PayloadDownstreamPaths = @PayloadDownstreamPaths_70bf2ca4,
  @PayloadUpstreamPaths = @PayloadUpstreamPaths_70bf2ca4,
  @PayloadSelfReadPaths = @PayloadSelfReadPaths_70bf2ca4,
  @PayloadSelfReadPaths_Clear = 1,
  @PayloadSelfWritePaths = @PayloadSelfWritePaths_70bf2ca4,
  @PayloadSelfWritePaths_Clear = 1,
  @PayloadScope = @PayloadScope_70bf2ca4,
  @PayloadScope_Clear = 1,
  @FinalPayloadValidation = @FinalPayloadValidation_70bf2ca4,
  @FinalPayloadValidation_Clear = 1,
  @FinalPayloadValidationMode = @FinalPayloadValidationMode_70bf2ca4,
  @FinalPayloadValidationMaxRetries = @FinalPayloadValidationMaxRetries_70bf2ca4,
  @MaxCostPerRun = @MaxCostPerRun_70bf2ca4,
  @MaxCostPerRun_Clear = 1,
  @MaxTokensPerRun = @MaxTokensPerRun_70bf2ca4,
  @MaxTokensPerRun_Clear = 1,
  @MaxIterationsPerRun = @MaxIterationsPerRun_70bf2ca4,
  @MaxTimePerRun = @MaxTimePerRun_70bf2ca4,
  @MaxTimePerRun_Clear = 1,
  @MinExecutionsPerRun = @MinExecutionsPerRun_70bf2ca4,
  @MinExecutionsPerRun_Clear = 1,
  @MaxExecutionsPerRun = @MaxExecutionsPerRun_70bf2ca4,
  @MaxExecutionsPerRun_Clear = 1,
  @StartingPayloadValidation = @StartingPayloadValidation_70bf2ca4,
  @StartingPayloadValidation_Clear = 1,
  @StartingPayloadValidationMode = @StartingPayloadValidationMode_70bf2ca4,
  @DefaultPromptEffortLevel = @DefaultPromptEffortLevel_70bf2ca4,
  @DefaultPromptEffortLevel_Clear = 1,
  @ChatHandlingOption = @ChatHandlingOption_70bf2ca4,
  @ChatHandlingOption_Clear = 1,
  @DefaultArtifactTypeID = @DefaultArtifactTypeID_70bf2ca4,
  @DefaultArtifactTypeID_Clear = 1,
  @OwnerUserID = @OwnerUserID_70bf2ca4,
  @InvocationMode = @InvocationMode_70bf2ca4,
  @ArtifactCreationMode = @ArtifactCreationMode_70bf2ca4,
  @FunctionalRequirements = @FunctionalRequirements_70bf2ca4,
  @FunctionalRequirements_Clear = 1,
  @TechnicalDesign = @TechnicalDesign_70bf2ca4,
  @TechnicalDesign_Clear = 1,
  @InjectNotes = @InjectNotes_70bf2ca4,
  @MaxNotesToInject = @MaxNotesToInject_70bf2ca4,
  @NoteInjectionStrategy = @NoteInjectionStrategy_70bf2ca4,
  @InjectExamples = @InjectExamples_70bf2ca4,
  @MaxExamplesToInject = @MaxExamplesToInject_70bf2ca4,
  @ExampleInjectionStrategy = @ExampleInjectionStrategy_70bf2ca4,
  @IsRestricted = @IsRestricted_70bf2ca4,
  @MessageMode = @MessageMode_70bf2ca4,
  @MaxMessages = @MaxMessages_70bf2ca4,
  @MaxMessages_Clear = 1,
  @AttachmentStorageProviderID = @AttachmentStorageProviderID_70bf2ca4,
  @AttachmentStorageProviderID_Clear = 1,
  @AttachmentRootPath = @AttachmentRootPath_70bf2ca4,
  @AttachmentRootPath_Clear = 1,
  @InlineStorageThresholdBytes = @InlineStorageThresholdBytes_70bf2ca4,
  @InlineStorageThresholdBytes_Clear = 1,
  @AgentTypePromptParams = @AgentTypePromptParams_70bf2ca4,
  @AgentTypePromptParams_Clear = 1,
  @ScopeConfig = @ScopeConfig_70bf2ca4,
  @ScopeConfig_Clear = 1,
  @NoteRetentionDays = @NoteRetentionDays_70bf2ca4,
  @ExampleRetentionDays = @ExampleRetentionDays_70bf2ca4,
  @AutoArchiveEnabled = @AutoArchiveEnabled_70bf2ca4,
  @RerankerConfiguration = @RerankerConfiguration_70bf2ca4,
  @RerankerConfiguration_Clear = 1,
  @CategoryID = @CategoryID_70bf2ca4,
  @CategoryID_Clear = 1,
  @AllowEphemeralClientTools = @AllowEphemeralClientTools_70bf2ca4,
  @DefaultStorageAccountID = @DefaultStorageAccountID_70bf2ca4,
  @DefaultStorageAccountID_Clear = 1,
  @SearchScopeAccess = @SearchScopeAccess_70bf2ca4,
  @AcceptUnregisteredFiles = @AcceptUnregisteredFiles_70bf2ca4,
  @DefaultCoAgentID = @DefaultCoAgentID_70bf2ca4,
  @DefaultCoAgentID_Clear = 1,
  @TypeConfiguration = @TypeConfiguration_70bf2ca4,
  @TypeConfiguration_Clear = 1,
  @AllowMemoryWrite = @AllowMemoryWrite_70bf2ca4,
  @RecordingDefault = @RecordingDefault_70bf2ca4,
  @RecordingDefault_Clear = 1,
  @RecordingStorageProviderID = @RecordingStorageProviderID_70bf2ca4,
  @RecordingStorageProviderID_Clear = 1,
  @DefaultMediaCollectionID = @DefaultMediaCollectionID_70bf2ca4,
  @DefaultMediaCollectionID_Clear = 1,
  @SupportsPlanMode = @SupportsPlanMode_70bf2ca4,
  @AcceptsSkills = @AcceptsSkills_70bf2ca4,
  @SkillActivationMode = @SkillActivationMode_70bf2ca4,
  @RequirePlanMode = @RequirePlanMode_70bf2ca4;

GO

-- Save MJ: AI Agent Prompts (core SP call only)
DECLARE @ID_82adb7dc UNIQUEIDENTIFIER,
@AgentID_82adb7dc UNIQUEIDENTIFIER,
@PromptID_82adb7dc UNIQUEIDENTIFIER,
@Purpose_82adb7dc NVARCHAR(MAX),
@ExecutionOrder_82adb7dc INT,
@ConfigurationID_82adb7dc UNIQUEIDENTIFIER,
@Status_82adb7dc NVARCHAR(20),
@ContextBehavior_82adb7dc NVARCHAR(50),
@ContextMessageCount_82adb7dc INT
SET
  @ID_82adb7dc = '912BEFEB-F91E-4928-82D1-1D34DDDD5AA9'
SET
  @AgentID_82adb7dc = 'EA768C7C-66B6-4A60-BB5E-2D669E571FB1'
SET
  @PromptID_82adb7dc = 'D9514B6F-567B-431B-8718-6C93DFFCD0D9'
SET
  @ExecutionOrder_82adb7dc = 0
SET
  @Status_82adb7dc = N'Active'
SET
  @ContextBehavior_82adb7dc = N'Complete' EXEC [${mjSchema}].spCreateAIAgentPrompt @ID = @ID_82adb7dc,
  @AgentID = @AgentID_82adb7dc,
  @PromptID = @PromptID_82adb7dc,
  @Purpose = @Purpose_82adb7dc,
  @Purpose_Clear = 1,
  @ExecutionOrder = @ExecutionOrder_82adb7dc,
  @ConfigurationID = @ConfigurationID_82adb7dc,
  @ConfigurationID_Clear = 1,
  @Status = @Status_82adb7dc,
  @ContextBehavior = @ContextBehavior_82adb7dc,
  @ContextMessageCount = @ContextMessageCount_82adb7dc,
  @ContextMessageCount_Clear = 1;

GO


-- End of SQL Logging Session
-- Session ID: 43b4572b-29aa-429a-81aa-a3945557e449
-- Completed: 2026-07-08T03:20:39.514Z
-- Duration: 835ms
-- Total Statements: 29
