/* SQL text to update entity field related entity name field map for entity field ID 01CA1C9F-8DAF-4542-9977-DA5C21A3A53F */
EXEC [${flyway:defaultSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='01CA1C9F-8DAF-4542-9977-DA5C21A3A53F', @RelatedEntityNameFieldMap='Task'

/* SQL text to update entity field related entity name field map for entity field ID 0F4ABC14-3877-448F-9858-E8B7FC352E13 */
EXEC [${flyway:defaultSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='0F4ABC14-3877-448F-9858-E8B7FC352E13', @RelatedEntityNameFieldMap='Task'

/* Base View SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: vwArtifacts
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Artifacts
-----               SCHEMA:      ${flyway:defaultSchema}_Committees
-----               BASE TABLE:  Artifact
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[vwArtifacts]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}_Committees].[vwArtifacts];
GO

CREATE VIEW [${flyway:defaultSchema}_Committees].[vwArtifacts]
AS
SELECT
    a.*,
    mjCommitteesCommittee_CommitteeID.[Name] AS [Committee],
    mjCommitteesMeeting_MeetingID.[Title] AS [Meeting],
    mjCommitteesAgendaItem_AgendaItemID.[Title] AS [AgendaItem],
    mjCommitteesActionItem_ActionItemID.[Title] AS [ActionItem],
    mjCommitteesArtifactType_ArtifactTypeID.[Name] AS [ArtifactType],
    mjBizAppsCommonPerson_UploadedByPersonID.[DisplayName] AS [UploadedByPerson],
    mjBizAppsTasksTask_TaskID.[Name] AS [Task]
FROM
    [${flyway:defaultSchema}_Committees].[Artifact] AS a
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[Committee] AS mjCommitteesCommittee_CommitteeID
  ON
    [a].[CommitteeID] = mjCommitteesCommittee_CommitteeID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[Meeting] AS mjCommitteesMeeting_MeetingID
  ON
    [a].[MeetingID] = mjCommitteesMeeting_MeetingID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[AgendaItem] AS mjCommitteesAgendaItem_AgendaItemID
  ON
    [a].[AgendaItemID] = mjCommitteesAgendaItem_AgendaItemID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[ActionItem] AS mjCommitteesActionItem_ActionItemID
  ON
    [a].[ActionItemID] = mjCommitteesActionItem_ActionItemID.[ID]
INNER JOIN
    [${flyway:defaultSchema}_Committees].[ArtifactType] AS mjCommitteesArtifactType_ArtifactTypeID
  ON
    [a].[ArtifactTypeID] = mjCommitteesArtifactType_ArtifactTypeID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_BizAppsCommon].[vwPeopleExtended] AS mjBizAppsCommonPerson_UploadedByPersonID
  ON
    [a].[UploadedByPersonID] = mjBizAppsCommonPerson_UploadedByPersonID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_BizAppsTasks].[Task] AS mjBizAppsTasksTask_TaskID
  ON
    [a].[TaskID] = mjBizAppsTasksTask_TaskID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}_Committees].[vwArtifacts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* Base View Permissions SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: Permissions for vwArtifacts
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}_Committees].[vwArtifacts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: spCreateArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Artifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[spCreateArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}_Committees].[spCreateArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}_Committees].[spCreateArtifact]
    @ID uniqueidentifier = NULL,
    @CommitteeID uniqueidentifier,
    @MeetingID uniqueidentifier,
    @AgendaItemID uniqueidentifier,
    @ActionItemID uniqueidentifier,
    @Title nvarchar(255),
    @Description nvarchar(MAX),
    @ArtifactTypeID uniqueidentifier,
    @Provider nvarchar(50),
    @ExternalID nvarchar(500),
    @URL nvarchar(2000),
    @MimeType nvarchar(100),
    @FileSize bigint,
    @UploadedByPersonID uniqueidentifier,
    @TaskID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}_Committees].[Artifact]
            (
                [ID],
                [CommitteeID],
                [MeetingID],
                [AgendaItemID],
                [ActionItemID],
                [Title],
                [Description],
                [ArtifactTypeID],
                [Provider],
                [ExternalID],
                [URL],
                [MimeType],
                [FileSize],
                [UploadedByPersonID],
                [TaskID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @CommitteeID,
                @MeetingID,
                @AgendaItemID,
                @ActionItemID,
                @Title,
                @Description,
                @ArtifactTypeID,
                @Provider,
                @ExternalID,
                @URL,
                @MimeType,
                @FileSize,
                @UploadedByPersonID,
                @TaskID
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}_Committees].[Artifact]
            (
                [CommitteeID],
                [MeetingID],
                [AgendaItemID],
                [ActionItemID],
                [Title],
                [Description],
                [ArtifactTypeID],
                [Provider],
                [ExternalID],
                [URL],
                [MimeType],
                [FileSize],
                [UploadedByPersonID],
                [TaskID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @CommitteeID,
                @MeetingID,
                @AgendaItemID,
                @ActionItemID,
                @Title,
                @Description,
                @ArtifactTypeID,
                @Provider,
                @ExternalID,
                @URL,
                @MimeType,
                @FileSize,
                @UploadedByPersonID,
                @TaskID
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}_Committees].[vwArtifacts] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spCreateArtifact] TO [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spCreateArtifact] TO [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: spUpdateArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Artifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[spUpdateArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}_Committees].[spUpdateArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}_Committees].[spUpdateArtifact]
    @ID uniqueidentifier,
    @CommitteeID uniqueidentifier,
    @MeetingID uniqueidentifier,
    @AgendaItemID uniqueidentifier,
    @ActionItemID uniqueidentifier,
    @Title nvarchar(255),
    @Description nvarchar(MAX),
    @ArtifactTypeID uniqueidentifier,
    @Provider nvarchar(50),
    @ExternalID nvarchar(500),
    @URL nvarchar(2000),
    @MimeType nvarchar(100),
    @FileSize bigint,
    @UploadedByPersonID uniqueidentifier,
    @TaskID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}_Committees].[Artifact]
    SET
        [CommitteeID] = @CommitteeID,
        [MeetingID] = @MeetingID,
        [AgendaItemID] = @AgendaItemID,
        [ActionItemID] = @ActionItemID,
        [Title] = @Title,
        [Description] = @Description,
        [ArtifactTypeID] = @ArtifactTypeID,
        [Provider] = @Provider,
        [ExternalID] = @ExternalID,
        [URL] = @URL,
        [MimeType] = @MimeType,
        [FileSize] = @FileSize,
        [UploadedByPersonID] = @UploadedByPersonID,
        [TaskID] = @TaskID
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}_Committees].[vwArtifacts] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}_Committees].[vwArtifacts]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spUpdateArtifact] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Artifact table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[trgUpdateArtifact]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}_Committees].[trgUpdateArtifact];
GO
CREATE TRIGGER [${flyway:defaultSchema}_Committees].trgUpdateArtifact
ON [${flyway:defaultSchema}_Committees].[Artifact]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}_Committees].[Artifact]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}_Committees].[Artifact] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spUpdateArtifact] TO [cdp_Developer], [cdp_Integration]



/* spDelete SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: spDeleteArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Artifact
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[spDeleteArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}_Committees].[spDeleteArtifact];
GO

CREATE PROCEDURE [${flyway:defaultSchema}_Committees].[spDeleteArtifact]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}_Committees].[Artifact]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spDeleteArtifact] TO [cdp_Developer], [cdp_Integration]
    

/* spDelete Permissions for Artifacts */

GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spDeleteArtifact] TO [cdp_Developer], [cdp_Integration]



/* Root ID Function SQL for Comments.ParentCommentID */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comments
-- Item: fnCommentParentCommentID_GetRootID
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
------------------------------------------------------------
----- ROOT ID FUNCTION FOR: [Comment].[ParentCommentID]
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[fnCommentParentCommentID_GetRootID]', 'IF') IS NOT NULL
    DROP FUNCTION [${flyway:defaultSchema}_Committees].[fnCommentParentCommentID_GetRootID];
GO

CREATE FUNCTION [${flyway:defaultSchema}_Committees].[fnCommentParentCommentID_GetRootID]
(
    @RecordID uniqueidentifier,
    @ParentID uniqueidentifier
)
RETURNS TABLE
AS
RETURN
(
    WITH CTE_RootParent AS (
        SELECT
            [ID],
            [ParentCommentID],
            [ID] AS [RootParentID],
            0 AS [Depth]
        FROM
            [${flyway:defaultSchema}_Committees].[Comment]
        WHERE
            [ID] = COALESCE(@ParentID, @RecordID)

        UNION ALL

        SELECT
            c.[ID],
            c.[ParentCommentID],
            c.[ID] AS [RootParentID],
            p.[Depth] + 1 AS [Depth]
        FROM
            [${flyway:defaultSchema}_Committees].[Comment] c
        INNER JOIN
            CTE_RootParent p ON c.[ID] = p.[ParentCommentID]
        WHERE
            p.[Depth] < 100
    )
    SELECT TOP 1
        [RootParentID] AS RootID
    FROM
        CTE_RootParent
    WHERE
        [ParentCommentID] IS NULL
    ORDER BY
        [RootParentID]
);
GO


/* Base View SQL for Comments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comments
-- Item: vwComments
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Comments
-----               SCHEMA:      ${flyway:defaultSchema}_Committees
-----               BASE TABLE:  Comment
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[vwComments]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}_Committees].[vwComments];
GO

CREATE VIEW [${flyway:defaultSchema}_Committees].[vwComments]
AS
SELECT
    c.*,
    mjCommitteesCommittee_CommitteeID.[Name] AS [Committee],
    mjCommitteesMeeting_MeetingID.[Title] AS [Meeting],
    mjCommitteesAgendaItem_AgendaItemID.[Title] AS [AgendaItem],
    mjCommitteesActionItem_ActionItemID.[Title] AS [ActionItem],
    mjCommitteesArtifact_ArtifactID.[Title] AS [Artifact],
    mjCommitteesComment_ParentCommentID.[CommentText] AS [ParentComment],
    mjBizAppsCommonPerson_PersonID.[DisplayName] AS [Person],
    mjBizAppsTasksTask_TaskID.[Name] AS [Task],
    root_ParentCommentID.RootID AS [RootParentCommentID]
FROM
    [${flyway:defaultSchema}_Committees].[Comment] AS c
INNER JOIN
    [${flyway:defaultSchema}_Committees].[Committee] AS mjCommitteesCommittee_CommitteeID
  ON
    [c].[CommitteeID] = mjCommitteesCommittee_CommitteeID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[Meeting] AS mjCommitteesMeeting_MeetingID
  ON
    [c].[MeetingID] = mjCommitteesMeeting_MeetingID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[AgendaItem] AS mjCommitteesAgendaItem_AgendaItemID
  ON
    [c].[AgendaItemID] = mjCommitteesAgendaItem_AgendaItemID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[ActionItem] AS mjCommitteesActionItem_ActionItemID
  ON
    [c].[ActionItemID] = mjCommitteesActionItem_ActionItemID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[Artifact] AS mjCommitteesArtifact_ArtifactID
  ON
    [c].[ArtifactID] = mjCommitteesArtifact_ArtifactID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_Committees].[Comment] AS mjCommitteesComment_ParentCommentID
  ON
    [c].[ParentCommentID] = mjCommitteesComment_ParentCommentID.[ID]
INNER JOIN
    [${flyway:defaultSchema}_BizAppsCommon].[vwPeopleExtended] AS mjBizAppsCommonPerson_PersonID
  ON
    [c].[PersonID] = mjBizAppsCommonPerson_PersonID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}_BizAppsTasks].[Task] AS mjBizAppsTasksTask_TaskID
  ON
    [c].[TaskID] = mjBizAppsTasksTask_TaskID.[ID]
OUTER APPLY
    [${flyway:defaultSchema}_Committees].[fnCommentParentCommentID_GetRootID]([c].[ID], [c].[ParentCommentID]) AS root_ParentCommentID
GO
GRANT SELECT ON [${flyway:defaultSchema}_Committees].[vwComments] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* Base View Permissions SQL for Comments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comments
-- Item: Permissions for vwComments
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}_Committees].[vwComments] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for Comments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comments
-- Item: spCreateComment
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Comment
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[spCreateComment]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}_Committees].[spCreateComment];
GO

CREATE PROCEDURE [${flyway:defaultSchema}_Committees].[spCreateComment]
    @ID uniqueidentifier = NULL,
    @CommitteeID uniqueidentifier,
    @MeetingID uniqueidentifier,
    @AgendaItemID uniqueidentifier,
    @ActionItemID uniqueidentifier,
    @ArtifactID uniqueidentifier,
    @ParentCommentID uniqueidentifier,
    @PersonID uniqueidentifier,
    @CommentText nvarchar(MAX),
    @MentionedPersonIDs nvarchar(MAX),
    @IsResolved bit = NULL,
    @TaskID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}_Committees].[Comment]
            (
                [ID],
                [CommitteeID],
                [MeetingID],
                [AgendaItemID],
                [ActionItemID],
                [ArtifactID],
                [ParentCommentID],
                [PersonID],
                [CommentText],
                [MentionedPersonIDs],
                [IsResolved],
                [TaskID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @CommitteeID,
                @MeetingID,
                @AgendaItemID,
                @ActionItemID,
                @ArtifactID,
                @ParentCommentID,
                @PersonID,
                @CommentText,
                @MentionedPersonIDs,
                ISNULL(@IsResolved, 0),
                @TaskID
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}_Committees].[Comment]
            (
                [CommitteeID],
                [MeetingID],
                [AgendaItemID],
                [ActionItemID],
                [ArtifactID],
                [ParentCommentID],
                [PersonID],
                [CommentText],
                [MentionedPersonIDs],
                [IsResolved],
                [TaskID]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @CommitteeID,
                @MeetingID,
                @AgendaItemID,
                @ActionItemID,
                @ArtifactID,
                @ParentCommentID,
                @PersonID,
                @CommentText,
                @MentionedPersonIDs,
                ISNULL(@IsResolved, 0),
                @TaskID
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}_Committees].[vwComments] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spCreateComment] TO [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for Comments */

GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spCreateComment] TO [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for Comments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comments
-- Item: spUpdateComment
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Comment
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[spUpdateComment]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}_Committees].[spUpdateComment];
GO

CREATE PROCEDURE [${flyway:defaultSchema}_Committees].[spUpdateComment]
    @ID uniqueidentifier,
    @CommitteeID uniqueidentifier,
    @MeetingID uniqueidentifier,
    @AgendaItemID uniqueidentifier,
    @ActionItemID uniqueidentifier,
    @ArtifactID uniqueidentifier,
    @ParentCommentID uniqueidentifier,
    @PersonID uniqueidentifier,
    @CommentText nvarchar(MAX),
    @MentionedPersonIDs nvarchar(MAX),
    @IsResolved bit,
    @TaskID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}_Committees].[Comment]
    SET
        [CommitteeID] = @CommitteeID,
        [MeetingID] = @MeetingID,
        [AgendaItemID] = @AgendaItemID,
        [ActionItemID] = @ActionItemID,
        [ArtifactID] = @ArtifactID,
        [ParentCommentID] = @ParentCommentID,
        [PersonID] = @PersonID,
        [CommentText] = @CommentText,
        [MentionedPersonIDs] = @MentionedPersonIDs,
        [IsResolved] = @IsResolved,
        [TaskID] = @TaskID
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}_Committees].[vwComments] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}_Committees].[vwComments]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spUpdateComment] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Comment table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[trgUpdateComment]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}_Committees].[trgUpdateComment];
GO
CREATE TRIGGER [${flyway:defaultSchema}_Committees].trgUpdateComment
ON [${flyway:defaultSchema}_Committees].[Comment]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}_Committees].[Comment]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}_Committees].[Comment] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for Comments */

GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spUpdateComment] TO [cdp_Developer], [cdp_Integration]



/* spDelete SQL for Comments */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Comments
-- Item: spDeleteComment
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Comment
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}_Committees].[spDeleteComment]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}_Committees].[spDeleteComment];
GO

CREATE PROCEDURE [${flyway:defaultSchema}_Committees].[spDeleteComment]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}_Committees].[Comment]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spDeleteComment] TO [cdp_Developer], [cdp_Integration]
    

/* spDelete Permissions for Comments */

GRANT EXECUTE ON [${flyway:defaultSchema}_Committees].[spDeleteComment] TO [cdp_Developer], [cdp_Integration]



/* Set field properties for entity */

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET DefaultInView = 1
               WHERE ID = '5A58A761-4AF9-4371-9A9F-34D05590AE87'
               AND AutoUpdateDefaultInView = 1
            

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET DefaultInView = 1
               WHERE ID = '366A1BF2-227D-4319-AB2C-7F2ADF29FB5F'
               AND AutoUpdateDefaultInView = 1
            

/* Set field properties for entity */

               UPDATE [${flyway:defaultSchema}].[EntityField]
               SET DefaultInView = 1
               WHERE ID = '5F7B6CEA-5252-4BB0-93F4-B2AA60E21A86'
               AND AutoUpdateDefaultInView = 1
            

/* Set categories for 16 fields */

-- UPDATE Entity Field Category Info Artifacts.ID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '7C276534-B46C-4035-BB64-49BAA7C0A2AB' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.CommitteeID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '0B9C54AC-5206-423A-A353-056E9A24A732' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.MeetingID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'C53FC5A3-01E2-4AB3-A84B-58B8BE1DE136' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.AgendaItemID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '9300A125-AEEA-43E1-9C41-C303C7E8899E' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.Title 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '0944B1F6-E52E-4D8E-8882-64EB1CAC8BED' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.Description 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '1BC69300-429A-466B-832F-D86F2A280F8A' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.ArtifactTypeID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'E948E1B1-A591-40BD-B215-A4B3F723CA7F' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.Provider 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'DABCF878-B859-43E1-81AD-1B3B5FAC8420' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.ExternalID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '7A1ADBDC-FE0E-411B-80CD-0A67460D40F0' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.URL 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = 'URL',
   CodeType = NULL
WHERE 
   ID = '5A58A761-4AF9-4371-9A9F-34D05590AE87' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.MimeType 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '305360C2-44D9-416C-9B98-F4AB947F41EC' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.FileSize 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '366A1BF2-227D-4319-AB2C-7F2ADF29FB5F' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.UploadedByPersonID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Uploaded By',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '17786941-BBE8-4E5A-9DAB-3A070ECF4953' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.__mj_CreatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'ACEC7865-D05E-44D2-A692-3A43E15CF6F7' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.__mj_UpdatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '8037C2BD-F555-4FA7-BC61-0340D91A64C0' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Artifacts.TaskID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   Category = 'Related Entities',
   GeneratedFormSection = 'Category',
   DisplayName = 'Task',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '01CA1C9F-8DAF-4542-9977-DA5C21A3A53F' AND AutoUpdateCategory = 1

/* Set categories for 13 fields */

-- UPDATE Entity Field Category Info Comments.ID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'FE9A0C3D-8B21-4311-AE9B-E6F2FE3466ED' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.__mj_CreatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '8878AB25-82A8-4363-949F-CF49E859CDDA' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.__mj_UpdatedAt 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'AE166C9F-68FD-498E-B5CB-E33F10287D66' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.CommitteeID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '45D954CA-FBED-4FBD-AACF-B8EC5F6DFEA1' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.MeetingID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B96B872B-94A0-422B-B1F2-C5756DF46E0B' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.AgendaItemID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'A3B47465-C656-4B1A-83B5-548670731FF6' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.ArtifactID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'AFC0ED45-BB27-41F3-A014-6DC713EAC021' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.ParentCommentID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '1879C6B8-7969-4E39-AF36-52E28898CDBD' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.PersonID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '5F7B6CEA-5252-4BB0-93F4-B2AA60E21A86' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.TaskID 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   Category = 'Associations',
   GeneratedFormSection = 'Category',
   DisplayName = 'Task',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '0F4ABC14-3877-448F-9858-E8B7FC352E13' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.CommentText 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'FAD8C690-0A7C-492E-823F-2EFE7BAF7F7E' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.MentionedPersonIDs 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Mentioned Persons',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = '6AB58027-5DBB-445C-81B3-54BED4B6E3E7' AND AutoUpdateCategory = 1

-- UPDATE Entity Field Category Info Comments.IsResolved 
UPDATE [${flyway:defaultSchema}].[EntityField]
SET 
   GeneratedFormSection = 'Category',
   DisplayName = 'Resolved',
   ExtendedType = NULL,
   CodeType = NULL
WHERE 
   ID = 'B3D661E2-C7CD-487D-837F-FA30CCF5531A' AND AutoUpdateCategory = 1

/* Generated Validation Functions for MJ.BizApps.Tasks:Task Dependencies */
-- CHECK constraint for MJ.BizApps.Tasks:Task Dependencies @ Table Level was newly set or modified since the last generation of the validation function, the code was regenerated and updating the GeneratedCode table with the new generated validation function
INSERT INTO [${flyway:defaultSchema}].[GeneratedCode] (CategoryID, GeneratedByModelID, GeneratedAt, Language, Status, Source, Code, Description, Name, LinkedEntityID, LinkedRecordPrimaryKey)
                      VALUES ((SELECT ID FROM ${flyway:defaultSchema}.vwGeneratedCodeCategories WHERE Name='CodeGen: Validators'), '8E1BADD5-D593-4F9B-90D4-BF6D8AFA74A0', GETUTCDATE(), 'TypeScript','Approved', '([TaskID]<>[DependsOnTaskID])', 'public ValidateTaskIDNotEqualDependsOnTaskID(result: ValidationResult) {
	// Ensure the task does not reference itself as a dependency
	if (this.TaskID != null && this.DependsOnTaskID != null && this.TaskID === this.DependsOnTaskID) {
		result.Errors.push(new ValidationErrorInfo(
			"TaskID",
			"Task cannot depend on itself; TaskID and DependsOnTaskID must be different.",
			this.TaskID,
			ValidationErrorType.Failure
		));
	}
}', 'A task must not be listed as depending on itself; the TaskID and DependsOnTaskID fields must be different for each record.', 'ValidateTaskIDNotEqualDependsOnTaskID', 'E0238F34-2837-EF11-86D4-6045BDEE16E6', '82B3253E-8E72-4BF6-8F94-82EBD13084D9');

            

/* Generated Validation Functions for MJ.BizApps.Tasks:Task Template Item Dependencies */
-- CHECK constraint for MJ.BizApps.Tasks:Task Template Item Dependencies @ Table Level was newly set or modified since the last generation of the validation function, the code was regenerated and updating the GeneratedCode table with the new generated validation function
INSERT INTO [${flyway:defaultSchema}].[GeneratedCode] (CategoryID, GeneratedByModelID, GeneratedAt, Language, Status, Source, Code, Description, Name, LinkedEntityID, LinkedRecordPrimaryKey)
                      VALUES ((SELECT ID FROM ${flyway:defaultSchema}.vwGeneratedCodeCategories WHERE Name='CodeGen: Validators'), '8E1BADD5-D593-4F9B-90D4-BF6D8AFA74A0', GETUTCDATE(), 'TypeScript','Approved', '([ItemID]<>[DependsOnItemID])', 'public ValidateItemIDNotEqualsDependsOnItemID(result: ValidationResult) {
	// Ensure both IDs are present before comparing (fields are non‑null, but check for safety)
	if (this.ItemID != null && this.DependsOnItemID != null && this.ItemID === this.DependsOnItemID) {
		result.Errors.push(new ValidationErrorInfo(
			"ItemID",
			"An item cannot depend on itself. ItemID must be different from DependsOnItemID.",
			this.ItemID,
			ValidationErrorType.Failure
		));
	}
}', 'An item cannot depend on itself; the ItemID must be different from the DependsOnItemID to ensure a valid dependency relationship.', 'ValidateItemIDNotEqualsDependsOnItemID', 'E0238F34-2837-EF11-86D4-6045BDEE16E6', '19CD22D9-4E20-499C-B9D2-2390271CDC0E');

            

/* Generated Validation Functions for MJ.BizApps.Tasks:Tasks */
-- CHECK constraint for MJ.BizApps.Tasks:Tasks: Field: PercentComplete was newly set or modified since the last generation of the validation function, the code was regenerated and updating the GeneratedCode table with the new generated validation function
INSERT INTO [${flyway:defaultSchema}].[GeneratedCode] (CategoryID, GeneratedByModelID, GeneratedAt, Language, Status, Source, Code, Description, Name, LinkedEntityID, LinkedRecordPrimaryKey)
                      VALUES ((SELECT ID FROM ${flyway:defaultSchema}.vwGeneratedCodeCategories WHERE Name='CodeGen: Validators'), '8E1BADD5-D593-4F9B-90D4-BF6D8AFA74A0', GETUTCDATE(), 'TypeScript','Approved', '([PercentComplete]>=(0) AND [PercentComplete]<=(100))', 'public ValidatePercentCompleteRange(result: ValidationResult) {
	if (this.PercentComplete < 0 || this.PercentComplete > 100) {
		result.Errors.push(new ValidationErrorInfo(
			"PercentComplete",
			"Percent complete must be between 0 and 100.",
			this.PercentComplete,
			ValidationErrorType.Failure
		));
	}
}', 'Percent complete must be a value from 0 up to 100, ensuring the progress percentage stays within a valid range for tracking task completion', 'ValidatePercentCompleteRange', 'DF238F34-2837-EF11-86D4-6045BDEE16E6', '4F8293B3-B230-4669-843E-8059F114BB77');

            

